### ISSUE TITLE
Finding out when and how to also show story instance dungeons in the dungeon list

### ISSUE THREAD

**Issue by Hartie95** [Anime-Game-Servers/Grasscutter-Quests#3]
currently we need to manually enter story dungeons like 1, 1001 and 1003.
We need to figure out when we need to add them to the dungeon lists, and how to do it.

**Comment by KingRainbow44** [comment]
fixed in commit [unstable-quests/0de69cd](https://github.com/Grasscutters/Grasscutter/commit/0de69cd1fa16cd4f196b97556208bdb3b511e819) (please close so i can stop clicking on this issue)
