### ISSUE TITLE
Find a way to select which script groups to load, and which to replace 

### ISSUE THREAD

**Issue by Hartie95** [Anime-Game-Servers/Grasscutter-Quests#4]
Currently the server just loads most scripts and spawns in them, and ignores things like replacements or business.
This leads to many monsters being spawned at some places.
We need to find out how we should propperly manage these groups.

**Comment by millet6** [comment]
Open the big world script, and the monsters will disappear in batches
开启大世界脚本批量怪物将会消失

**Comment by Hartie95** [comment]
> Open the big world script, and the monsters will disappear in batches 开启大世界脚本批量怪物将会消失

That has its own problems, since disabling scripts in big word will break more quests and everything else that's dynamic and needs scripts. 
So either way the script loading system needs to be reworked

**Comment by millet6** [comment]
Yeah, you're right

**Comment by StartForKiller** [comment]
I'm working on this

**Comment by StartForKiller** [comment]
Anyways, the current lua backend it's broken on a lot of parts

**Comment by Hartie95** [comment]
A good chunck of this is now done thanks to @StartForKiller .
Loading of activity groups and loading of common scriipts is still missing.

I'm currently working on handling including common lluas properly in luaj, which is kinda a pain xD

**Comment by Hartie95** [comment]
General activity group loading and common group loading is now implemented in AnimeGamesLua and just needs to be used on demand.
For ways of loading required scripts without the workaround, a ticket in AnimeGamesLua will be opened.
