### ISSUE TITLE
[Bug] Stuck in middle of dungeon with nil access errors

### ISSUE THREAD

**Issue by mkZH0740** [Anime-Game-Servers/Grasscutter-Quests#77]
**Did you look for other closed issues that have the same problem?**
couldn't find similar problem

**Describe the bug**
Dungeon get stucked because next stage won't generate

**Which branch did you use?**
  Grasscutter version: 1.7.1
  Git Hash: 2643c6b3

**Screenshots**
<img width="866" alt="image" src="https://github.com/Anime-Game-Servers/Grasscutter-Quests/assets/56063116/29f32b7e-1051-4992-9f8e-92ac9ac5467c">
<img width="862" alt="image" src="https://github.com/Anime-Game-Servers/Grasscutter-Quests/assets/56063116/427854c9-b5b6-407c-90e2-80c0e505fd48">

**Additional context**
I was doing the quest Act I - Wind, Courage, and Wings: Outrider Style. 
I have no idea what causes this, it might be that the script is broken.

**Comment by scooterboo** [comment]
Fist of all, this repo's version is something like 1.2.0 not 1.7.1. You might be thinking of grasscutters/grasscutters.

Second of all, go into your resources folder in script/scene/3 and find the group that is associated with your group number in your error. Then scroll down to the line it talks about right before the attempted to index nil part. For the first screenshot this is line 115 and the second screenshot is line 182. That will help you find what causes this.

**Comment by mkZH0740** [comment]
got it, thx, ill try to do that to figure out the cause.

**Comment by Hartie95** [comment]
> Fist of all, this repo's version is something like 1.2.0 not 1.7.1. You might be thinking of grasscutters/grasscutter.
> 
> Second of all, go into your resources folder in script/scene/3 and find the group that is associated with your group number in your error. Then scroll down to the line it talks about right before the attempted to index nil part. For the first screenshot this is line 115 and the second screenshot is line 182. That will help you find what causes this.

in 133002406 its probably either the access to the global var gadgets[i] or defs.bornPoints[idx] returns nil.

But yeah, doesn't look like he used this fork, based on the commit hash and version.
