### ISSUE TITLE
[Bug] Unexpected Power - Hold Elemental Skill - Slimes keep respawning

### ISSUE THREAD

**Issue by scooterboo** [Anime-Game-Servers/Grasscutter-Quests#83]
**Describe the bug**
In quest 35303 Unexpected Power - Hold Elemental Skill, slimes keep respawning when you kill them with an elemental blast

**How to replicate:**
After Paimon on the cliff, go to the statue island, get the cutscene, try to get off the island, and then try to continue the quest. You might not need to try to get off the island to replicate.
Holding the elemental button is not causing the quest to continue.

**Notes:**
Maybe a problem with the implementation of QUEST_CONTENT_SKILL? not getting the EvtDoSkillSuccNotify packet? Maybe an ability problem?

**Which branch did you use?**
multi_proto
Grasscutter version: 1.4.4-dev-59e2d2b4
Lua: LuaJ and JNLua

**Screenshots**

https://github.com/Anime-Game-Servers/Grasscutter-Quests/assets/1877986/9245dcab-3205-49f2-a89e-2f4327a30e67

**Comment by Hartie95** [comment]
This seems to be a resources problem, the skillId was mistranslated to overtime, should be fixed by now

**Comment by scooterboo** [comment]
I am on JNLua now and the new resources. It is not fixed.

**Comment by scooterboo** [comment]
I was not on new resources. I am now on new resources and it is fixed!
