### ISSUE TITLE
[Bug] repairing the Holy Lyre gives you amber

### ISSUE THREAD

**Issue by scooterboo** [Anime-Game-Servers/Grasscutter-Quests#93]
**Describe the bug**
Repairing the Holy Lyre gives you amber:
![image](https://github.com/Anime-Game-Servers/Grasscutter-Quests/assets/1877986/e3926cb7-3960-4e99-b99f-fa7a62331184)

This is a resources problem.

I'll dm you my thoughts.

**Comment by Hartie95** [comment]
should be fixed with https://github.com/Anime-Game-Servers/CustomGCResources/pull/5/commits/fa05b9b8f481faf5a65b91ea0a9421d2bdaa5f10

**Comment by scooterboo** [comment]
This would have fixed it too:
https://github.com/Anime-Game-Servers/CustomGCResources/pull/10

**Comment by scooterboo** [comment]
Confirmed fixed after applying https://github.com/Anime-Game-Servers/CustomGCResources/pull/10

**Comment by scooterboo** [comment]
https://github.com/Anime-Game-Servers/CustomGCResources/pull/10 merged
