### ISSUE TITLE
[Bug] The wind barrier in act 3 does not disperse

### ISSUE THREAD

**Issue by scooterboo** [Anime-Game-Servers/Grasscutter-Quests#98]
**Describe the bug**
in `Hurdle - Disperse the wind barrier 38803` the wind barrier doesn't disperse.

**How to replicate:**
/q add 38803 and then if it doesn't finish on it's own: /q finish 38803

**Notes:**
There's some swapped arguments in org/anime_game_servers/gi_lua/ScriptLib:
![image](https://github.com/Anime-Game-Servers/Grasscutter-Quests/assets/1877986/1d9b190f-eb74-4b5d-bc9d-d3cc56a3dc30)

KillByConfigIdParams goes (configId, groupId, entityType) not (groupId, configId, entityType)

![image](https://github.com/Anime-Game-Servers/Grasscutter-Quests/assets/1877986/54029c20-a22c-4575-839f-5dce24e4284c)

I tested by swapping them in ScriptLibHandler because I don't know how to edit gi_lua:
![image](https://github.com/Anime-Game-Servers/Grasscutter-Quests/assets/1877986/20ae83e6-8b2c-4f30-9526-7217f6b829bc)
 Works great!

**Which branch did you use?**
multi_proto
Grasscutter version: 1.4.4-dev-f1cdbc02
Lua: JNLua

**Screenshots**

https://github.com/Anime-Game-Servers/Grasscutter-Quests/assets/1877986/b4b0d177-6c8f-466d-af0f-7029cd663634

**Comment by Hartie95** [comment]
should be fixed in https://github.com/Hartie95/AnimeGamesLua/commit/34e9f21cabdfe2af57bcad3e7e893e19cfee54e9

**Comment by scooterboo** [comment]
Confirmed fixed!
